#!/bin/bash

# target temperature
TARGET=58

# starting frequency
FREQUENCY=3000

function update {
	# apply preferences
	for i in {0..15}
	do
		sudo cpufreq-set -c $i -f "${FREQUENCY}MHz"
	done
}

while true
do
	# current package temperature
	CURR_TEMP=$(sensors | grep Package | cut -d "+" -f2 | cut -d "." -f1)

	# speed up if temperature is too low
	if [[ $CURR_TEMP -lt $TARGET ]] && [[ $FREQUENCY -lt 3600 ]]
	then
		FREQUENCY=$(( $FREQUENCY + 100 ))
		update
	fi

	# slow down if temperature is too high
	if [[ $CURR_TEMP -gt $TARGET ]] && [[ $FREQUENCY -gt 1200 ]]
	then
		FREQUENCY=$(( $FREQUENCY - 100 ))
		update
	fi

	sleep "1s"
done
